from graphics import *
win= GraphWin('My Circle', 1920, 1280)
win.setBackground('lightBlue')


def Jeopardy_Game_Board():
#Title Button One -----  TITLE  BUTTON (NOT INTERACTIVE)  -----
    ColumnOneButtonOne= Rectangle(Point(50,100), Point(250, 200))
    ColumnOneButtonOne.setOutline('#13066E')
    ColumnOneButtonOne.setFill('#13066E')
    ColumnOneButtonOne.draw(win)
    TitleOne= Text(Point(150,150), "Science")
    TitleOne.setSize(20)
    TitleOne.setStyle("bold")
    TitleOne.setTextColor("white")
    TitleOne.draw(win)
   
    

#Button Two
    ColumnOneButtonTwo= Rectangle(Point(50,230), Point(250, 330))
    ColumnOneButtonTwo.setOutline('#13066E')
    ColumnOneButtonTwo.setFill('#13066E')
    ColumnOneButtonTwo.draw(win)
    HundredCOne= Text(Point(150,280), "100")
    HundredCOne.setSize(34)
    HundredCOne.setStyle("bold")
    HundredCOne.setTextColor("white")
    HundredCOne.draw(win)
    
    
#Bottom 3
    ColumnOneButtonThree= Rectangle(Point(50,360), Point(250, 460))
    ColumnOneButtonThree.setOutline('#13066E')
    ColumnOneButtonThree.setFill('#13066E')
    ColumnOneButtonThree.draw(win)
    TwoHundredCOne= Text(Point(150,410), "200")
    TwoHundredCOne.setSize(34)
    TwoHundredCOne.setStyle("bold")
    TwoHundredCOne.setTextColor("white")
    TwoHundredCOne.draw(win)
    
     
#Bottom 4
    ColumnOneButtonFour= Rectangle(Point(50,490), Point(250, 590))
    ColumnOneButtonFour.setOutline('#13066E')
    ColumnOneButtonFour.setFill('#13066E')
    ColumnOneButtonFour.draw(win)
    ThreeHundredCOne= Text(Point(150,540), "300")
    ThreeHundredCOne.setSize(34)
    ThreeHundredCOne.setStyle("bold")
    ThreeHundredCOne.setTextColor("white")
    ThreeHundredCOne.draw(win)
     
#Button 5
    ColumnOneButtonFive= Rectangle(Point(50,620), Point(250, 720))
    ColumnOneButtonFive.setOutline('#13066E')
    ColumnOneButtonFive.setFill('#13066E')
    ColumnOneButtonFive.draw(win)
    FourHundredCOne= Text(Point(150,670), "400")
    FourHundredCOne.setSize(34)
    FourHundredCOne.setStyle("bold")
    FourHundredCOne.setTextColor("white")
    FourHundredCOne.draw(win)
     
#Button 6
    ColumnOneButtonSix= Rectangle(Point(50,750), Point(250, 850))
    ColumnOneButtonSix.setOutline('#13066E')
    ColumnOneButtonSix.setFill('#13066E')
    ColumnOneButtonSix.draw(win)
    FiveHundredCOne= Text(Point(150,800), "500")
    FiveHundredCOne.setSize(34)
    FiveHundredCOne.setStyle("bold")
    FiveHundredCOne.setTextColor("white")
    FiveHundredCOne.draw(win)
     
#Column Two Button One -----  TITLE  BUTTON (NOT INTERACTIVE)  -----
    ColumnTwoButtonOne= Rectangle(Point(300,100), Point(500, 200))
    ColumnTwoButtonOne.setOutline('#13066E')
    ColumnTwoButtonOne.setFill('#13066E')
    ColumnTwoButtonOne.draw(win)
    TitleTwo= Text(Point(400,150), "American History")
    TitleTwo.setSize(17)
    TitleTwo.setStyle("bold")
    TitleTwo.setTextColor("white")
    TitleTwo.draw(win)
     
    #Button Two
    # ColumnTwoButtonTwo= Rectangle(Point(300,230), Point(500, 330))
    # ColumnTwoButtonTwo.setOutline('#13066E')
    # ColumnTwoButtonTwo.setFill('#13066E')
    # ColumnTwoButtonTwo.draw(win)
    # HundredCTwo= Text(Point(400,280), "100")
    # HundredCTwo.setSize(34)
    # HundredCTwo.setStyle("bold")
    # HundredCTwo.setTextColor("white")
    # HundredCTwo.draw(win)
#Buttom Three
    ColumnTwoButtonThree= Rectangle(Point(300,230), Point(500, 330))
    ColumnTwoButtonThree.setOutline('#13066E')
    ColumnTwoButtonThree.setFill('#13066E')
    ColumnTwoButtonThree.draw(win)
    TwoHundredCTwo= Text(Point(400,280), "100")
    TwoHundredCTwo.setSize(34)
    TwoHundredCTwo.setStyle("bold")
    TwoHundredCTwo.setTextColor("white")
    TwoHundredCTwo.draw(win)
     
#Button Four
    ColumnTwoButtonFour= Rectangle(Point(300,360), Point(500, 460))
    ColumnTwoButtonFour.setOutline('#13066E')
    ColumnTwoButtonFour.setFill('#13066E')
    ColumnTwoButtonFour.draw(win)
    ThreeHundredCTwo= Text(Point(400,410), "200")
    ThreeHundredCTwo.setSize(34)
    ThreeHundredCTwo.setStyle("bold")
    ThreeHundredCTwo.setTextColor("white")
    ThreeHundredCTwo.draw(win)
     
#Button Five
    ColumnTwoButtonFive= Rectangle(Point(300,490), Point(500, 590))
    ColumnTwoButtonFive.setOutline('#13066E')
    ColumnTwoButtonFive.setFill('#13066E')
    ColumnTwoButtonFive.draw(win)
    FourHundredCTwo= Text(Point(400,540), "300")
    FourHundredCTwo.setSize(34)
    FourHundredCTwo.setStyle("bold")
    FourHundredCTwo.setTextColor("white")
    FourHundredCTwo.draw(win)
     
#Button Six
    ColumnTwoButtonSix= Rectangle(Point(300,620), Point(500, 720))
    ColumnTwoButtonSix.setOutline('#13066E')
    ColumnTwoButtonSix.setFill('#13066E')
    ColumnTwoButtonSix.draw(win)
    FiveHundredCTwo= Text(Point(400,670), "400")
    FiveHundredCTwo.setSize(34)
    FiveHundredCTwo.setStyle("bold")
    FiveHundredCTwo.setTextColor("white")
    FiveHundredCTwo.draw(win)
     
# Column Two Button Seven
    ColumnTwoButtonSeven= Rectangle(Point(300,750), Point(500, 850))
    ColumnTwoButtonSeven.setOutline('#13066E')
    ColumnTwoButtonSeven.setFill('#13066E')
    ColumnTwoButtonSeven.draw(win)
    FiveHundredCTwo= Text(Point(400,800), "500")
    FiveHundredCTwo.setSize(34)
    FiveHundredCTwo.setStyle("bold")
    FiveHundredCTwo.setTextColor("white")
    FiveHundredCTwo.draw(win)
     
#Column Three Button One -----  TITLE  BUTTON (NOT INTERACTIVE)  -----
    ColumnThreeButtonOne= Rectangle(Point(600,100), Point(800, 200))
    ColumnThreeButtonOne.setOutline('#13066E')
    ColumnThreeButtonOne.setFill('#13066E')
    ColumnThreeButtonOne.draw(win)
    TitleThree= Text(Point(700,150), "Literature")
    TitleThree.setSize(20)
    TitleThree.setStyle("bold")
    TitleThree.setTextColor("white")
    TitleThree.draw(win)
     
    #Column Three Button Two
    # ColumnThreeButtonTwo= Rectangle(Point(600,230), Point(800, 330))
    # ColumnThreeButtonTwo.setOutline('#13066E')
    # ColumnThreeButtonTwo.setFill('#13066E')
    # ColumnThreeButtonTwo.draw(win)
    # HundredCTwo= Text(Point(700,280), "100")
    # HundredCTwo.setSize(34)
    # HundredCTwo.setStyle("bold")
    # HundredCTwo.setTextColor("white")
    # HundredCTwo.draw(win)
#Column Three Buttom Three
    ColumnThreeButtonThree= Rectangle(Point(600,230), Point(800, 330))
    ColumnThreeButtonThree.setOutline('#13066E')
    ColumnThreeButtonThree.setFill('#13066E')
    ColumnThreeButtonThree.draw(win)
    HundredCTwo= Text(Point(700,280), "100")
    HundredCTwo.setSize(34)
    HundredCTwo.setStyle("bold")
    HundredCTwo.setTextColor("white")
    HundredCTwo.draw(win)
     
#Column Three Button Four
    ColumnThreeButtonFour= Rectangle(Point(600,360), Point(800, 460))
    ColumnThreeButtonFour.setOutline('#13066E')
    ColumnThreeButtonFour.setFill('#13066E')
    ColumnThreeButtonFour.draw(win)
    TwoHundredCTwo= Text(Point(700,410), "200")
    TwoHundredCTwo.setSize(34)
    TwoHundredCTwo.setStyle("bold")
    TwoHundredCTwo.setTextColor("white")
    TwoHundredCTwo.draw(win)
     
#Column Three Button Five
    ColumnThreeButtonFive= Rectangle(Point(600,490), Point(800, 590))
    ColumnThreeButtonFive.setOutline('#13066E')
    ColumnThreeButtonFive.setFill('#13066E')
    ColumnThreeButtonFive.draw(win)
    ThreeHundredCTwo= Text(Point(700,540), "300")
    ThreeHundredCTwo.setSize(34)
    ThreeHundredCTwo.setStyle("bold")
    ThreeHundredCTwo.setTextColor("white")
    ThreeHundredCTwo.draw(win)
     
#Column Three Button Six
    ColumnThreeButtonSix= Rectangle(Point(600,620), Point(800, 720))
    ColumnThreeButtonSix.setOutline('#13066E')
    ColumnThreeButtonSix.setFill('#13066E')
    ColumnThreeButtonSix.draw(win)
    FourHundredCTwo= Text(Point(700,670), "400")
    FourHundredCTwo.setSize(34)
    FourHundredCTwo.setStyle("bold")
    FourHundredCTwo.setTextColor("white")
    FourHundredCTwo.draw(win)
     
#Column Three Button Seven
    ColumnThreeButtonSeven= Rectangle(Point(600,750), Point(800, 850))
    ColumnThreeButtonSeven.setOutline('#13066E')
    ColumnThreeButtonSeven.setFill('#13066E')
    ColumnThreeButtonSeven.draw(win)
    FiveHundredCTwo= Text(Point(700,800), "500")
    FiveHundredCTwo.setSize(34)
    FiveHundredCTwo.setStyle("bold")
    FiveHundredCTwo.setTextColor("white")
    FiveHundredCTwo.draw(win)
     
#Column Four Button One -----  TITLE  BUTTON (NOT INTERACTIVE)  -----
    ColumnFourButtonOne= Rectangle(Point(900,100), Point(1100, 200))
    ColumnFourButtonOne.setOutline('#13066E')
    ColumnFourButtonOne.setFill('#13066E')
    ColumnFourButtonOne.draw(win)
    TitleFour= Text(Point(1000,150), "Colleges")
    TitleFour.setSize(20)
    TitleFour.setStyle("bold")
    TitleFour.setTextColor("white")
    TitleFour.draw(win)
     
    #Column Four Button Two
    # ColumnFourButtonTwo= Rectangle(Point(900,230), Point(1100, 330))
    # ColumnFourButtonTwo.setOutline('#13066E')
    # ColumnFourButtonTwo.setFill('#13066E')
    # ColumnFourButtonTwo.draw(win)
    # HundredCThree= Text(Point(1000,280), "100")
    # HundredCThree.setSize(34)
    # HundredCThree.setStyle("bold")
    # HundredCThree.setTextColor("white")
    # HundredCThree.draw(win)
#Column Four Buttom Three
    ColumnFourButtonTwo= Rectangle(Point(900,230), Point(1100, 330))
    ColumnFourButtonTwo.setOutline('#13066E')
    ColumnFourButtonTwo.setFill('#13066E')
    ColumnFourButtonTwo.draw(win)
    HundredCTwo= Text(Point(1000,280), "100")
    HundredCTwo.setSize(34)
    HundredCTwo.setStyle("bold")
    HundredCTwo.setTextColor("white")
    HundredCTwo.draw(win)
     
#Column Four Button Four
    ColumnFourButtonThree= Rectangle(Point(900,360), Point(1100, 460))
    ColumnFourButtonThree.setOutline('#13066E')
    ColumnFourButtonThree.setFill('#13066E')
    ColumnFourButtonThree.draw(win)
    HundredCThree= Text(Point(1000,410), "200")
    HundredCThree.setSize(34)
    HundredCThree.setStyle("bold")
    HundredCThree.setTextColor("white")
    HundredCThree.draw(win)
     
#Column Four Button Five
    ColumnFourButtonFive= Rectangle(Point(900,490), Point(1100, 590))
    ColumnFourButtonFive.setOutline('#13066E')
    ColumnFourButtonFive.setFill('#13066E')
    ColumnFourButtonFive.draw(win)
    HundredCThree= Text(Point(1000,540), "300")
    HundredCThree.setSize(34)
    HundredCThree.setStyle("bold")
    HundredCThree.setTextColor("white")
    HundredCThree.draw(win)
     
#Column Four Button Six
    ColumnFourButtonSix= Rectangle(Point(900,620), Point(1100, 720))
    ColumnFourButtonSix.setOutline('#13066E')
    ColumnFourButtonSix.setFill('#13066E')
    ColumnFourButtonSix.draw(win)
    HundredCThree= Text(Point(1000,670), "400")
    HundredCThree.setSize(34)
    HundredCThree.setStyle("bold")
    HundredCThree.setTextColor("white")
    HundredCThree.draw(win)
     
#Column Four Button Seven
    ColumnFourButtonSeven= Rectangle(Point(900,750), Point(1100, 850))
    ColumnFourButtonSeven.setOutline('#13066E')
    ColumnFourButtonSeven.setFill('#13066E')
    ColumnFourButtonSeven.draw(win)
    HundredCThree= Text(Point(1000,800), "500")
    HundredCThree.setSize(34)
    HundredCThree.setStyle("bold")
    HundredCThree.setTextColor("white")
    HundredCThree.draw(win)
     
#Column 5 Button One -----  TITLE  BUTTON (NOT INTERACTIVE)  -----
    ColumnFiveButtonOne= Rectangle(Point(1200,100), Point(1400, 200))
    ColumnFiveButtonOne.setOutline('#13066E')
    ColumnFiveButtonOne.setFill('#13066E')
    ColumnFiveButtonOne.draw(win)
    TitleFour= Text(Point(1300,150), "Word Origins")
    TitleFour.setSize(20)
    TitleFour.setStyle("bold")
    TitleFour.setTextColor("white")
    TitleFour.draw(win)
     
#Column Five Button Two
    ColumnFiveButtonTwo= Rectangle(Point(1200,230), Point(1400, 330))
    ColumnFiveButtonTwo.setOutline('#13066E')
    ColumnFiveButtonTwo.setFill('#13066E')
    ColumnFiveButtonTwo.draw(win)
    HundredCTwo= Text(Point(1300,280), "100")
    HundredCTwo.setSize(34)
    HundredCTwo.setStyle("bold")
    HundredCTwo.setTextColor("white")
    HundredCTwo.draw(win)
     
    #Column Five Buttom Three
    # ColumnFiveButtonThree= Rectangle(Point(1200,230), Point(1400, 330))
    # ColumnFiveButtonThree.setOutline('#13066E')
    # ColumnFiveButtonThree.setFill('#13066E')
    # ColumnFiveButtonThree.draw(win)
    # HundredCThree= Text(Point(1300,2800), "200")
    # HundredCThree.setSize(34)
    # HundredCThree.setStyle("bold")
    # HundredCThree.setTextColor("white")
    # HundredCThree.draw(win)
#Column Five Button Four
    ColumnFiveButtonFour= Rectangle(Point(1200,360), Point(1400, 460))
    ColumnFiveButtonFour.setOutline('#13066E')
    ColumnFiveButtonFour.setFill('#13066E')
    ColumnFiveButtonFour.draw(win)
    HundredCFour= Text(Point(1300,410), "200")
    HundredCFour.setSize(34)
    HundredCFour.setStyle("bold")
    HundredCFour.setTextColor("white")
    HundredCFour.draw(win)
     
#Column Five Button Five
    ColumnFiveButtonFive= Rectangle(Point(1200,490), Point(1400, 590))
    ColumnFiveButtonFive.setOutline('#13066E')
    ColumnFiveButtonFive.setFill('#13066E')
    ColumnFiveButtonFive.draw(win)
    HundredCFive= Text(Point(1300,540), "300")
    HundredCFive.setSize(34)
    HundredCFive.setStyle("bold")
    HundredCFive.setTextColor("white")
    HundredCFive.draw(win)
     
#Column Five Button Six
    ColumnFiveButtonSix= Rectangle(Point(1200,620), Point(1400, 720))
    ColumnFiveButtonSix.setOutline('#13066E')
    ColumnFiveButtonSix.setFill('#13066E')
    ColumnFiveButtonSix.draw(win)
    HundredCSix= Text(Point(1300,670), "400")
    HundredCSix.setSize(34)
    HundredCSix.setStyle("bold")
    HundredCSix.setTextColor("white")
    HundredCSix.draw(win)
     
#Column Five Button Seven
    ColumnFiveButtonSeven= Rectangle(Point(1200,750), Point(1400, 850))
    ColumnFiveButtonSeven.setOutline('#13066E')
    ColumnFiveButtonSeven.setFill('#13066E')
    ColumnFiveButtonSeven.draw(win)
    HundredCSeven= Text(Point(1300,800), "500")
    HundredCSeven.setSize(34)
    HundredCSeven.setStyle("bold")
    HundredCSeven.setTextColor("white")
    HundredCSeven.draw(win)
     
#Column Six Button One -----  TITLE  BUTTON (NOT INTERACTIVE)  -----
    ColumnSixButtonOne= Rectangle(Point(1500,100), Point(1700, 200))
    ColumnSixButtonOne.setOutline('#13066E')
    ColumnSixButtonOne.setFill('#13066E')
    ColumnSixButtonOne.draw(win)
    TitleFour= Text(Point(1600,150), "Before and After")
    TitleFour.setSize(18)
    TitleFour.setStyle("bold")
    TitleFour.setTextColor("white")
    TitleFour.draw(win)
     
    #Column Six Button Two
    # ColumnSixButtonTwo= Rectangle(Point(1500,230), Point(1700, 330))
    # ColumnSixButtonTwo.setOutline('#13066E')
    # ColumnSixButtonTwo.setFill('#13066E')
    # ColumnSixButtonTwo.draw(win)
    # HundredCTwo= Text(Point(1600,280), "100")
    # HundredCTwo.setSize(34)
    # HundredCTwo.setStyle("bold")
    # HundredCTwo.setTextColor("white")
    # HundredCTwo.draw(win)
#Column Six Buttom Three
    ColumnSixButtonThree= Rectangle(Point(1500,230), Point(1700, 330))
    ColumnSixButtonThree.setOutline('#13066E')
    ColumnSixButtonThree.setFill('#13066E')
    ColumnSixButtonThree.draw(win)
    HundredCThree= Text(Point(1600,280), "100")
    HundredCThree.setSize(34)
    HundredCThree.setStyle("bold")
    HundredCThree.setTextColor("white")
    HundredCThree.draw(win)
     
#Column Six Button Four
    ColumnSixButtonFour= Rectangle(Point(1500,360), Point(1700, 460))
    ColumnSixButtonFour.setOutline('#13066E')
    ColumnSixButtonFour.setFill('#13066E')
    ColumnSixButtonFour.draw(win)
    HundredCFour= Text(Point(1600,410), "200")
    HundredCFour.setSize(34)
    HundredCFour.setStyle("bold")
    HundredCFour.setTextColor("white")
    HundredCFour.draw(win)
     
#Column Six Button Five
    ColumnSixButtonFive= Rectangle(Point(1500,490), Point(1700, 590))
    ColumnSixButtonFive.setOutline('#13066E')
    ColumnSixButtonFive.setFill('#13066E')
    ColumnSixButtonFive.draw(win)
    HundredCFive= Text(Point(1600,540), "300")
    HundredCFive.setSize(34)
    HundredCFive.setStyle("bold")
    HundredCFive.setTextColor("white")
    HundredCFive.draw(win)
     
#Column Six Button Six
    ColumnSixButtonSix= Rectangle(Point(1500,620), Point(1700, 720))
    ColumnSixButtonSix.setOutline('#13066E')
    ColumnSixButtonSix.setFill('#13066E')
    ColumnSixButtonSix.draw(win)
    HundredCSix= Text(Point(1600,670), "400")
    HundredCSix.setSize(34)
    HundredCSix.setStyle("bold")
    HundredCSix.setTextColor("white")
    HundredCSix.draw(win)
    
     
#Column Six Button Seven
    ColumnSixButtonSeven= Rectangle(Point(1500,750), Point(1700, 850))
    ColumnSixButtonSeven.setOutline('#13066E')
    ColumnSixButtonSeven.setFill('#13066E')
    ColumnSixButtonSeven.draw(win)
    HundredCSeven= Text(Point(1600,800), "500")
    HundredCSeven.setSize(34)
    HundredCSeven.setStyle("bold")
    HundredCSeven.setTextColor("white")
    HundredCSeven.draw(win)
     
Jeopardy_Game_Board()
clickPoint=win.getMouse()
xValue= clickPoint.getX()
yValue= clickPoint.getY()
def ColumnOneButtonOneclicker():
    if 50<xValue<250 and 230<yValue<330:
        ScienceQOne= Image(Point(960,300), "actual_science(100)question.png")
        ScienceQOne.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnOneButtonOneclicker()
def ColumnOneButtonTwoclicker():
    if 50<xValue<250 and 360<yValue<460:
        ScienceQTwo= Image(Point(960,300), "SCIENCE(200)QUESTION.png")
        ScienceQTwo.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnOneButtonTwoclicker()
def ColumnOneButtonThreeclicker():
    if 50<xValue<250 and 490<yValue<590:
        ScienceQThree= Image(Point(960,300), "SCIENCE(300)qUESIOTN.png")
        ScienceQThree.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnOneButtonThreeclicker()
def ColumnOneButtonFourclicker():
    if 50<xValue<250 and 620<yValue<720:
        ScienceQFour= Image(Point(960,300), "SCIENCE(400)QUESTION.png")
        ScienceQFour.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnOneButtonFourclicker()
def ColumnOneButtonFiveclicker():
    if 50<xValue<250 and 750<yValue<850:
        ScienceQFive= Image(Point(960,300), "SCIENCE(500)QUESTION.png")
        ScienceQFive.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnOneButtonFiveclicker()
def ColumnTwoButtonOneclicker():
    if 300<xValue<500 and 230<yValue<330:
        AmericanHistoryQOne= Image(Point(960,300), "AMERICANHISTORY(100)QUESTION.png")
        AmericanHistoryQOne.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnTwoButtonOneclicker()
def ColumnTwoButtonTwoclicker():
    if 300<xValue<500 and 360<yValue<460:
        AmericanHistoryQTwo= Image(Point(960,300), "AM-200.png")
        AmericanHistoryQTwo.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnTwoButtonTwoclicker()
def ColumnTwoButtonThreeclicker():
    if 300<xValue<500 and 490<yValue<590:
        AmericanHistoryQThree= Image(Point(960,300), "AM-300.png")
        AmericanHistoryQThree.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnTwoButtonThreeclicker()
def ColumnTwoButtonFourclicker():
    if 300<xValue<500 and 360<yValue<460:
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnTwoButtonTwoclicker()
def ColumnTwoButtonFiveclicker():
    if 300<xValue<500 and 620<yValue<720:
        AmericanHistoryQFour= Image(Point(960,300), "AM-400.png")
        AmericanHistoryQFour.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnTwoButtonFiveclicker()
def ColumnTwoButtonSixclicker():
    if 300<xValue<500 and 750<yValue<850:
        AmericanHistoryQFive= Image(Point(960,300), "AM-500.png")
        AmericanHistoryQFive.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnTwoButtonSixclicker()
def ColumnThreeButtonOneclicker():
    if 600<xValue<800 and 230<yValue<330:
        LiteratureQOne= Image(Point(960,300), "L-100 (1).png")
        LiteratureQOne.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnThreeButtonOneclicker()
def ColumnThreeButtonTwoclicker():
    if 600<xValue<800 and 360<yValue<460:
        LiteratureQTwo= Image(Point(960,300), "L-200.png")
        LiteratureQTwo.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnThreeButtonTwoclicker()
def ColumnThreeButtonThreeclicker():
    if 600<xValue<800 and 490<yValue<590:
        LiteratureQThree= Image(Point(960,300), "L-300.png")
        LiteratureQThree.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnThreeButtonThreeclicker()
def ColumnThreeButtonFourclicker():
    if 600<xValue<800 and 620<yValue<720:
        LiteratureQFour= Image(Point(960,300), "L-400.png")
        LiteratureQFour.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnThreeButtonFourclicker()
def ColumnThreeButtonFiveclicker():
    if 600<xValue<800 and 750<yValue<850:
        LiteratureQFive= Image(Point(960,300), "L-500.png")
        LiteratureQFive.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnThreeButtonFiveclicker()
def ColumnFourButtonOneclicker():
    if 900<xValue<1100 and 230<yValue<330:
        CollegesQOne= Image(Point(960,300), "Col-100.png")
        CollegesQOne.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFourButtonOneclicker()
def ColumnFourButtonTwoclicker():
    if 900<xValue<1100 and 360<yValue<460:
        CollegesQTwo= Image(Point(960,300), "Col-200.png")
        CollegesQTwo.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFourButtonTwoclicker()
def ColumnFourButtonThreeclicker():
    if 900<xValue<1100 and 490<yValue<590:
        CollegesQThree= Image(Point(960,300), "Col-300.png")
        CollegesQThree.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFourButtonThreeclicker()
def ColumnFourButtonFourclicker():
    if 900<xValue<1100 and 620<yValue<720:
        CollegesQFour= Image(Point(960,300), "Col-400.png")
        CollegesQFour.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFourButtonFourclicker()
def ColumnFourButtonFiveclicker():
    if 900<xValue<1100 and 750<yValue<850:
        CollegesQFive= Image(Point(960,300), "Col-500.png")
        CollegesQFive.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFourButtonFiveclicker()
def ColumnFiveButtonOneclicker():
    if 1200<xValue<1400 and 230<yValue<330:
        WordOriginsQOne= Image(Point(960,300), "WO-100.png")
        WordOriginsQOne.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFiveButtonOneclicker()
def ColumnFiveButtonTwoclicker():
    if 1200<xValue<1400 and 360<yValue<460:
        WordOriginsQTwo= Image(Point(960,300), "WO-200.png")
        WordOriginsQTwo.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFiveButtonTwoclicker()
def ColumnFiveButtonThreeclicker():
    if 1200<xValue<1400 and 490<yValue<590:
        WordOriginsQThree= Image(Point(960,300), "WO-300.png")
        WordOriginsQThree.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFiveButtonThreeclicker()
def ColumnFiveButtonFourclicker():
    if 1200<xValue<1400 and 620<yValue<720:
        WordOriginsQFour= Image(Point(960,300), "WO-400.png")
        WordOriginsQFour.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFiveButtonFourclicker()
def ColumnFiveButtonFiveclicker():
    if 1200<xValue<1400 and 750<yValue<850:
        WordOriginsQFive= Image(Point(960,300), "WO-500.png")
        WordOriginsQFive.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFiveButtonFiveclicker()
def ColumnFiveButtonSixclicker():
    if 1200<xValue<1400 and 880<yValue<980:
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnFiveButtonSixclicker()
def ColumnSixButtonOneclicker():
    if 1500<xValue<1700 and 230<yValue<330:
        PopCultureQOne= Image(Point(960,300), "PC-100.png")
        PopCultureQOne.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnSixButtonOneclicker()
def ColumnSixButtonTwoclicker():
    if 1500<xValue<1700 and 360<yValue<460:
        PopCultureQTwo= Image(Point(960,300), "PC-200.png")
        PopCultureQTwo.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnSixButtonTwoclicker()
def ColumnSixButtonThreeclicker():
    if 1500<xValue<1700 and 490<yValue<590:
        PopCultureQThree= Image(Point(960,300), "PC-300.png")
        PopCultureQThree.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnSixButtonThreeclicker()
def ColumnSixButtonFourclicker():
    if 1500<xValue<1700 and 620<yValue<720:
        PopCultureQFour= Image(Point(960,300), "PC-400.png")
        PopCultureQFour.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnSixButtonFourclicker()
def ColumnSixButtonFiveclicker():
    if 1500<xValue<1700 and 750<yValue<850:
        PopCultureQFive= Image(Point(960,300), "PC-500.png")
        PopCultureQFive.draw(win)
        inputBox= Entry(Point(960,640),39)
        inputBox.setFace("courier")
        inputBox.setSize(36)
        inputStr= inputBox.getText()
        inputBox.draw(win)
        keyString= win.getKey()
ColumnSixButtonFiveclicker()

def Card_Animations():
    #Slides go here
    Card_Animations()